import asyncio
import logging
import random

from fastapi import FastAPI, status
from fastapi.responses import JSONResponse


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger("python-observability-api")

app = FastAPI(
    title="Python Observability API",
    description="API mínima para uma PoC de observabilidade com OpenTelemetry.",
    version="0.1.0",
)


@app.get("/health")
async def health() -> dict[str, str]:
    return {
        "status": "healthy",
        "service": "python-observability-api",
    }


@app.get("/users")
async def list_users() -> dict[str, list[dict[str, int | str]]]:
    logger.info("Starting simulated user listing")
    return {
        "items": [
            {"id": 1, "name": "Alice"},
            {"id": 2, "name": "Bruno"},
        ]
    }


@app.post("/users/simulate-create", status_code=status.HTTP_201_CREATED)
async def simulate_create_user() -> dict[str, int | str]:
    logger.info("Starting simulated user creation")
    user = {
        "id": random.randint(3, 10_000),
        "name": "Generated User",
        "status": "created",
    }
    logger.info("Simulated user created successfully: id=%s", user["id"])
    return user


@app.get("/latency/random")
async def random_latency() -> dict[str, int | str]:
    delay_ms = random.randint(100, 5_000)
    logger.info("Simulating request latency: delay_ms=%s", delay_ms)
    await asyncio.sleep(delay_ms / 1_000)
    return {
        "status": "completed",
        "delay_ms": delay_ms,
    }


@app.get("/errors/handled")
async def handled_error() -> JSONResponse:
    logger.warning("Returning controlled simulated validation error")
    return JSONResponse(
        status_code=status.HTTP_400_BAD_REQUEST,
        content={
            "error": "simulated_validation_error",
            "message": "This is a controlled error generated by the API",
        },
    )


@app.get("/errors/unhandled")
async def unhandled_error() -> None:
    logger.error("Raising intentional unhandled exception")
    raise RuntimeError("Intentional unhandled error generated by the API")


@app.get("/external/simulate")
async def simulate_external_call() -> dict[str, int | str]:
    duration_ms = random.randint(200, 1_200)
    logger.info(
        "Simulating external provider call: provider=%s duration_ms=%s",
        "fake-external-provider",
        duration_ms,
    )
    await asyncio.sleep(duration_ms / 1_000)
    logger.info("Simulated external provider call completed successfully")
    return {
        "provider": "fake-external-provider",
        "status": "success",
        "duration_ms": duration_ms,
    }
