import asyncio
import logging
import random

from fastapi import FastAPI, status
from fastapi.responses import JSONResponse


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger("python-logs-api")

app = FastAPI(
    title="Python Logs API",
    description="API mínima para uma PoC de gerenciamento e visualização de logs.",
    version="0.1.0",
)


@app.get("/health")
async def health() -> dict[str, str]:
    logger.info("Health check requested")
    return {
        "status": "healthy",
        "service": "python-logs-api",
    }


@app.get("/success")
async def success() -> dict[str, str]:
    logger.info("Successful endpoint requested")
    return {
        "status": "success",
        "message": "Successful response generated",
    }


@app.get("/latency")
async def random_latency() -> dict[str, int | str]:
    delay_ms = random.randint(100, 5_000)
    logger.info("Simulating request latency: delay_ms=%s", delay_ms)
    await asyncio.sleep(delay_ms / 1_000)
    return {
        "status": "completed",
        "delay_ms": delay_ms,
    }


@app.get("/warning")
async def handled_error() -> JSONResponse:
    logger.warning("Returning controlled warning response")
    return JSONResponse(
        status_code=status.HTTP_400_BAD_REQUEST,
        content={
            "warning": "simulated_warning",
            "message": "This is a controlled warning generated by the API",
        },
    )


@app.get("/error/unhandled")
async def unhandled_error() -> None:
    logger.error("Raising intentional unhandled exception")
    raise RuntimeError("Intentional unhandled error generated by the API")
